sudo: false
language: ruby
rvm: 2.2.1

cache:
  bundler: true
  directories:
    - bower_components
    - node_modules

install:
  - ./bin/setup

script: bundle exec jekyll build

deploy:
  provider: script
  script: ./bin/deploy
  skip_cleanup: true