sudo: false
language: ruby
rvm: 2.2.1

cache:
  bundler: true
  directories:
    - bower_components
    - node_modules

install:
  - ./bin/setup.sh

script: bundle exec jekyll build

before_deploy:
  - chmod +x bin/deploy.sh

deploy:
  provider: script
  script: ./bin/deploy.sh
  skip_cleanup: true