language: ruby
rvm:
  - 2.4.1
script: ./script/cibuild
branches:
  only:
  - gh-pages
  - /pages-(.*)/
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
sudo: false
cache: bundler
notifications:
  email: false
