lang: ko
title: 김민석의 블로그
email: its@mskim.me
description: >-
  김민석의 개인 블로그
url: "http://blog.mskim.me"
repository: mskims/blog
baseurl: ""
permalink: "posts/:title/"
google_analytics: UA-97180334-1

# Build settings
markdown: kramdown
exclude: [vendor]
